FROM reactnativecommunity/react-native-android

EXPOSE 8081
EXPOSE 5037
EXPOSE 5554
EXPOSE 5555
EXPOSE 5900

WORKDIR /app

# COPY package*.json .

# RUN npm install

# COPY . .

CMD ["sh", "scripts/web.sh"]